#!/bin/bash
# ============================================================
# setup_remote_t32.sh
# 在远程机器上配置和启动 TRACE32 (RCL 模式)
#
# 使用方法:
#   1. 拷贝此脚本到远程机器
#   2. ssh user@remote "bash setup_remote_t32.sh"
#   或直接 scp 后远程执行
#
# 前置条件:
#   - 远程机器已安装 TRACE32 (t32mtc 在 PATH 或 /opt/t32_*/)
#   - JTAG 硬件已连接
# ============================================================

set -e

T32_INSTALL="${T32_INSTALL:-/opt/t32_202509}"
T32_BIN="${T32_INSTALL}/bin"
RCL_PORT="${RCL_PORT:-20000}"
WORK_DIR="/tmp/debugforge"

echo "============================================"
echo "  DebugForge: Remote TRACE32 Setup"
echo "  T32 Install: ${T32_INSTALL}"
echo "  RCL Port: ${RCL_PORT}"
echo "============================================"

# 1. 查找 t32mtc
if [ -x "${T32_BIN}/t32mtc" ]; then
    T32MT="${T32_BIN}/t32mtc"
elif command -v t32mtc &>/dev/null; then
    T32MT=$(command -v t32mtc)
else
    echo "[ERROR] t32mtc not found!"
    echo "  Tried: ${T32_BIN}/t32mtc"
    echo "  Set T32_INSTALL to your TRACE32 installation path"
    exit 1
fi
echo "  t32mtc: ${T32MT}"

# 2. 创建工作目录
mkdir -p "${WORK_DIR}/elf"
mkdir -p "${WORK_DIR}/cmm"
mkdir -p "${WORK_DIR}/tmp"
echo "  Work dir: ${WORK_DIR}"

# 3. 生成 RCL 配置
CONFIG_FILE="${WORK_DIR}/config_rcl.t32"
cat > "${CONFIG_FILE}" <<EOF
; Auto-generated by DebugForge setup_remote_t32.sh
; TRACE32 Remote Control Layer Configuration

SYS=${T32_INSTALL}
TMP=${WORK_DIR}/tmp

; Remote Control via TCP (required for PYRCL)
RCL=NETTCP
PORT=${RCL_PORT}
PACKLEN=4096

EOF

echo "  Config: ${CONFIG_FILE}"
cat "${CONFIG_FILE}"

# 4. 检查端口是否被占用
if command -v ss &>/dev/null; then
    if ss -tlnp 2>/dev/null | grep -q ":${RCL_PORT} "; then
        echo "  [WARN] Port ${RCL_PORT} already in use!"
        echo "  Another TRACE32 instance may be running"
        echo "  Kill it first or use a different port"
    fi
elif command -v netstat &>/dev/null; then
    if netstat -tlnp 2>/dev/null | grep -q ":${RCL_PORT} "; then
        echo "  [WARN] Port ${RCL_PORT} already in use!"
    fi
fi

# 5. 启动 TRACE32 (后台模式)
echo ""
echo "  Starting TRACE32 in background..."
echo "  Command: ${T32MT} -c ${CONFIG_FILE}"
echo ""
echo "  如需前台运行 (看 GUI):"
echo "    ${T32MT} -c ${CONFIG_FILE}"
echo ""
echo "  如需后台运行:"
echo "    nohup ${T32MT} -c ${CONFIG_FILE} &"
echo ""
echo "  测试连接 (从本地):"
echo "    python remote_debug.py --host $(hostname -I | awk '{print $1}')"
echo ""
echo "  ✓ Setup complete!"
echo "============================================"
